@startuml
header note-app
title Fetching notes\n(GET)
footer gaelceart
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
skinparam monochrome true
skinparam shadowing false
actor Client
participant "Route" as r
participant "Controller" as c
participant "Model" as m
entity "Notes\n(ORM)" as n
database SQL

autonumber 1.1
Client->r+:/notes
r->c+:getNotes()
c->m+:getNotes()
m->m+:getNotes()
m->n+:findAll()
n->SQL+:SELECT
return rows
return data
return data
return response
return response
return response
@enduml
